### ISSUE TITLE
How about working together on some optimizations?

### ISSUE THREAD

**Issue by metabench** [mateogianolio/vectorious#1]
I thought I should mention these things to see what direction you want to take the project in. I've done some work already that's a bit similar (not published yet) that simulates a table of numbers, and uses a typed array as the storage. Maybe you should use typed arrays here? What do you think? It would lose some flexibility because the typed array needs to be initialised with a fixed size, but operations are faster after that.

Then there is the possibility of writing C/C++ addon code. A few functions could be written in (mainly) C, using C++ bindings to node, and some operations would be a fair bit faster.

There would also then be the possibility of using SIMD to get higher speeds still, with intrinsics in the C++ code. I'd need to look into cross-platform compatibility for that, and find ways to only use particular SIMD instructions when they are available.

Which of these are directions you would be interested in taking vectorious?

**Comment by mateogianolio** [comment]
Rewriting some of the heavy computations in C/C++ would increase performance significantly and probably be the wisest next step of this project. I haven't tried writing any addons for node yet, is it possible to write functions in C and call them from node?

As for your other suggestion, I think it makes sense switching from dynamically allocated to statically allocated arrays to make it more compatible with C.

How would you like to start?

**Comment by metabench** [comment]
Yes, it's possible to write functions in C, and use C++ binding to connect it to node. I've been using https://github.com/rvagg/nan and know how to do it. I'm by no means an advanced C++ programmer (unless knowing a bit about some advanced topics makes me one). The style I'm using is a bit different to the NAN documentation and examples because I keep the node binding code more separate from the C/C++ code.

Something I've not tried doing yet is to have an object written in C++ that's made accessible to JavaScript. I don't know to what extent doing it that way would be useful here. Perhaps it would make better performance if (eventually) a whole class was written in C++. That may also make ensuring compatibility when no compiled code is available a bit more difficult.

Ensuring it still works without the C/C++ is still something we'd need to pay attention to. This may be best done on a new branch, and we test that branch before releasing it. I'm developing on Windows, I can easily test on OS X. Can you test on Linux?

**Comment by metabench** [comment]
The first step in optimizing victorious is to use typed arrays. They are quite a lot faster anyway.

For the purposes of convenience, we should support different types with DRY coding. I'm not sure that DRY coding when using different types of typed arrays will be as fast as having code that repeats. If a lot of code repetition is needed for best performance then I think a script to generate separate code files would help. I think for the meantime unless tests show otherwise we should use a DRY coding style.

**Comment by mateogianolio** [comment]
I'm developing in OS X and I can test on Linux. I'll have to look into the native abstractions library you linked to, but just from a quick glance it seems comprehensive and not that hard to use.

Should we set up a development branch which we can commit to without having to think about testing and then merge it with master whenever it is ready for production?

DRY is something I try to apply on all my projects and this is by no means an exception.

I just added you as a collaborator!

**Comment by metabench** [comment]
You should look at the tests section of it. The examples section is a bit lacking.

Also, when I looked at it there were no instructions on using typed arrays with it (or much about using them with node/iojs anywhere else).

Yesterday I encountered an error in using typed arrays when making an OpenCL wrapper, I'm not sure if the problem is with anything having changed in iojs or just some other problem with my coding.

If we use smalloc, we'd lose compatibility with anything but recent node/iojs versions.

Another possibility would be to use https://www.npmjs.com/package/ref-array.

For the moment, I think efforts should be made to use typed arrays rather than anything non-standard to JavaScript, but it's worth being aware of the alternatives.

**Comment by metabench** [comment]
https://github.com/rvagg/node-addon-examples/tree/master/6_object_wrap/nan shows how to wrap an object (you could call it a class) that gets created in JavaScript with a `new` call.

Other examples in that project would be useful. Though it shows how to wrap for different node versions, I'd recommend NAN because it ensures compatibility between different versions.
