### ISSUE TITLE
Investigate WebAssembly integration

### ISSUE THREAD

**Issue by mateogianolio** [mateogianolio/vectorious#102]
WebAssembly has reached Browser Preview and offers high performance typed array manipulation. It also makes it possible run C code in the browser, which might be very interesting for this project. We should investigate in which ways we can interface with WASM once it's released for general users.

**Comment by mateogianolio** [comment]
https://github.com/mdn/webassembly-examples

**Comment by Khalid-Nowaf** [comment]
I'm using victorious in the browser now, it would be awesome if I could leverage wasm integration and use BLAS in the browser!

**Comment by mateogianolio** [comment]
https://github.com/maierfelix/glmw

**Comment by metabench** [comment]
To what extent is it worth working on our own lower level implementations, or using existing libraries such as blas and glmw?

AssemblyScript looks very useful. Maybe it would be worth me coding in TypeScript to try it.

Since we already have (or soon will have) Vectorious in TypeScript, AssemblyScript looks like a good route to greater performance. I'm interested in that, as well as porting some JS code to C++ or Rust.

**Comment by mateogianolio** [comment]
Check this out. I did a quick translation of [the saxpy routine](https://github.com/Reference-LAPACK/lapack/blob/master/BLAS/SRC/saxpy.f) to TypeScript, WASM, C (Node.js addon) and C with system linked BLAS (nblas).

https://github.com/mateogianolio/native-wasm-c

**Comment by MaxGraey** [comment]
Unfortunately cost of calls wasm <-> host is pretty significant so using bench tools like `benchmark.js` is not good choice. See my notes: https://github.com/mateogianolio/native-wasm-c/pull/1#issue-255729913

**Comment by MaxGraey** [comment]
Also pretty interesting results if you slightly modify part of algorithm (changed for every lang version) from:
```ts
for (i = m; i < n; i += 4) {
   y[i + 0] += alpha * x[i + 0];
   y[i + 1] += alpha * x[i + 1];
   y[i + 2] += alpha * x[i + 2];
   y[i + 3] += alpha * x[i + 3];
}
```
to
```ts
for (; i < n; i += 4) {
   y[i + 0] += alpha * x[i + 0];
   y[i + 1] += alpha * x[i + 1];
   y[i + 2] += alpha * x[i + 2];
   y[i + 3] += alpha * x[i + 3];
}
```
Results:
```
ts x 221,134,839 ops/sec ±0.21% (96 runs sampled)
empty x 57,229,521 ops/sec ±0.42% (92 runs sampled)
wasm x 15.26 ops/sec ±0.72% (42 runs sampled)
c x 85.46 ops/sec ±1.00% (72 runs sampled)
vectorious x 98.55 ops/sec ±2.22% (71 runs sampled)
```

**Comment by mateogianolio** [comment]
Moved to discussions.
