### ISSUE TITLE
Interesting developments

### ISSUE THREAD

**Issue by mateogianolio** [mateogianolio/vectorious#108]
Let's use this issue to keep track of interesting usage of this library out in the wild.

* [datagrep](https://github.com/mjschock/datagrep)
  * A JavaScript Machine Learning Library by @mjschock.
* [synaptic2](https://github.com/synapticjs/synaptic2)
  * It seems like version 2 of the very popular [synaptic](https://github.com/cazala/synaptic) machine learning library by @cazala might be using vectorious under the hood.

**Comment by mjschock** [comment]
👍

**Comment by mateogianolio** [comment]
Moved to discussions.
