### ISSUE TITLE
Matrix lines 10-28 (constructor)... what do they do?

### ISSUE THREAD

**Issue by metabench** [mateogianolio/vectorious#11]
I already see it's using `[].slice.call(arguments, 0)` which I plan on changing.

With the other parts, it would help to have an explanation of what it should be doing, then I'll think about how to best express that in JavaScript. The answer to the question about the Vector constructor was very helpful 

There will be a lot of speed increases in Matrix.

**Comment by mateogianolio** [comment]
I removed the ```[].slice.call()```'s in my latest commit.

Usage example:

```javascript
var matrix = new Matrix();
// empty matrix

matrix = new Matrix(5);
// 5x5 matrix of zeros

matrix = new Matrix(new Vector(1, 2, 3));
// matrix containing [1, 2, 3] in first row

matrix = new Matrix(new Vector(1, 2, 3), new Vector(4, 5, 6));
// matrix containing [1, 2, 3] in first row and [4, 5, 6] in second

matrix = new Matrix(new Matrix(2))
// matrix containing [0, 0] in first row and [0, 0] in second
```

**Comment by metabench** [comment]
matrix = new Matrix(new Vector(1, 2, 3), new Vector(4, 5, 6));

That would be easier to write as 

    matrix = new Matrix([1, 2, 3], [4, 5, 6])

**Comment by metabench** [comment]
What do you think about an API change in the constructor allowing for that?

**Comment by mateogianolio** [comment]
You can already do

```javascript
matrix = new Matrix([[1, 2, 3], [4, 5, 6]])
```

so I'm not sure if it's really necessary.
