### ISSUE TITLE
Size of a vector

### ISSUE THREAD

**Issue by williamngan** [mateogianolio/vectorious#110]
Hi, I'm trying out vectorious (cool stuff!) and I cannot find a function to get the number of dimensions in a vector (eg, data.length). It would be good to have a `vector.size()` or `vector.ndims()`. And similarly for Matrix too?

**Comment by mateogianolio** [comment]
Hey William, have you tried `vector.length`? Similarly for matrices, `matrix.shape = [# of rows, # of columns]`. I'm glad you found it interesting :)

**Comment by mateogianolio** [comment]
Ah, thanks for pointing it out!
