### ISSUE TITLE
Matrix.get() doesn't throw an error when parameter is undefined

### ISSUE THREAD

**Issue by matthiasdv** [mateogianolio/vectorious#112]
I just noticed the `Matrix.get()` [function](https://github.com/mateogianolio/vectorious/wiki/Matrix-API#get) doesn't throw an error when called with an undefined parameter. 

For example: 

```
var i = undefined; // this could be by mistake
Matrix.get(i, j); // no error thrown here
```

It would be easier from a developer perspective to see where unintended behaviour is coming from. Willing to provide a pull request. But first; Is there a reasoning behind this?

**Comment by mateogianolio** [comment]
Thank you for submitting the issue. This should indeed result in an error.
