### ISSUE TITLE
Vector.random uses the wrong distribution

### ISSUE THREAD

**Issue by eweitnauer** [mateogianolio/vectorious#113]
The (https://github.com/mateogianolio/vectorious/wiki/Vector-API#random)[docs] state that `Vector.random` samples based on a normal distribution using the passed mean and standard deviation. What the code actually does is using a uniform distribution, which is not even centered around the passed mean, but around `(mean+deviation)/2`.

Here is the code in vector.js:

```js
Vector.random = function (count, deviation, mean, type) {
    deviation = deviation || 1;
    mean = mean || 0;
    return Vector.fill(count, function() {
      return deviation * Math.random() + mean;
    }, type);
  };
```

(A detail: when `0` is passed as the deviation, it should not be reset to `1`.)

**Comment by Beraliv** [comment]
@eweitnauer have a look at the problem, it must be already solved

**Comment by eweitnauer** [comment]
The pull request was only addressing an incorrect falsy test of the function arguments. The issue I described is still the same: Math.random() picks a number from a uniform distribution in [0,1). The code assumes that it returns a normal distribution centered around 0.

**Comment by mateogianolio** [comment]
Now I see you are completely right of course. The `random` function is weird. From reading the documentation one would think that it would sample from the standard normal distribution like [numpy.random.randn](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randn.html#numpy.random.randn) (see the **Notes** section). That's not even close to what it currently does. There is no distribution involved at all in `Vector.random`, it's just random sampling with weird parameters.

It needs to be rewritten or the documentation needs to be changed.

**Comment by mateogianolio** [comment]
https://arxiv.org/pdf/1303.6257.pdf
