### ISSUE TITLE
Automatic benchmarks

### ISSUE THREAD

**Issue by mateogianolio** [mateogianolio/vectorious#119]
Create proper benchmarks so we can compare performance between versions as we move forward. It would be awesome to be able to integrate it into the build process somehow.

**Comment by Beraliv** [comment]
One of the library I manage as a leader [nanoutils](https://github.com/nanoutils/nanoutils/blob/master/misc/cli/time.js) has performance tests. They can be integrated for your needs.

The only one issue is what info do you want to get and how you want to represent it

[nanoutils](https://github.com/nanoutils/nanoutils) has `TIMES.md` where a table shows the difference between two libraries.

**Comment by mateogianolio** [comment]
Cool, I’ll definitely check it out!

**Comment by metabench** [comment]
Maybe that would be useful... but that's probably not how I'll run my first benchmarks.

let ts = Date.now();
// run some code
console.log('tdiff:', Date.now() - ts);

Not saying that's the best way to benchmark, but patterns can emerge around simple measurements like that. I'll look into the more precise timing measurements too. I do recall taking some more precise measurements here and there.

Measurements are good to measure code improvements while working on those improvements. For long term comparison they are harder to keep to the same baseline. Variables include hardware, node version, OS, and of course the version of the code being run.

While keeping longer term benchmarks would be useful, there could be some inaccuracies with comparisons. Keeping track of the node version it's being run on makes sense - but I and many developers are most interested in the latest version of node. Tracking regressions with node version changes would be a useful capability.

I'm also interested in benchmarks that discover data on the Big O running times of algorithms.
