### ISSUE TITLE
Cross product

### ISSUE THREAD

**Issue by LukeSkyw** [mateogianolio/vectorious#125]
It seems that vectorious does not implement a cross product. Would you consider adding it?

**Comment by mateogianolio** [comment]
The reason is that the vector cross product only exists in the three- and seven- dimensional vector space.

**Comment by christianbender** [comment]
@mateogianolio Can we add a extra method for a cross vector product? The method could check if the vector has three or seven components and otherwise it throws an exception.

**Comment by mateogianolio** [comment]
Sure, should be simple enough to implement. Now that we use an underlying `NDArray` class it might make sense (in the future) to create separate `Vector<X>D` classes optimized for dimensions 2 to 4.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/1e44fd23f788d2f589f26344245765511e522e5b)

**Comment by christianbender** [comment]
@mateogianolio I would like work on this. Should I add this feature to the class [NDArray](https://github.com/mateogianolio/vectorious/blob/master/src/NDArray.ts) ? Or to the class [Vector](https://github.com/mateogianolio/vectorious/blob/master/src/Vector.ts) ?

**Comment by mateogianolio** [comment]
Nice! I say add it to `Vector`.

**Comment by christianbender** [comment]
@mateogianolio  I sended a pull request. Thanks

**Comment by mateogianolio** [comment]
Closed by 5.2.0 (#137)
