### ISSUE TITLE
Small vectors performance

### ISSUE THREAD

**Issue by baryluk** [mateogianolio/vectorious#129]
I see no performance benchmarks against other libraries for small vectors and matrices. I mean 2 3 4 wide ones. Or maybe just 16. These are extremely common in a lot of codes, especially dealing with 3d data, images, or physics engines, differential equation solving, etc.

Testing big vectors and matrices and routines that all forward to C BLAS, basically hides all JS overheads and inefficiencies, and is almost like cheating, and doesn't actually tell how fast the JS code is. :)

**Comment by mateogianolio** [comment]
Agreed, the benchmarks are very outdated (see #109  and #119). My original goal was to integrate the benchmarks into the build process, producing graphs like in #109 using matplotlib (see https://github.com/mateogianolio/matplotnode). However, I have a lot less time to work on this project now that I have a full time job.

That said, I am open to suggestions and if you want to contribute I encourage you to submit a pull request!
