### ISSUE TITLE
Implementing typed arrays

### ISSUE THREAD

**Issue by mateogianolio** [mateogianolio/vectorious#13]
Should we use a fixed array type or give the user the ability to choose (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays)?

I'm thinking the best would be to use ```Float64Array```, which is the equivalent of a C ```double```.

Like this:

```javascript```
var buffer = new ArrayBuffer(length * 8);
var values = new Float64Array(buffer);
```

**Comment by metabench** [comment]
I think allowing the user to choose the type would be best. Hopefully some code could allow for this to work without code repetition and at a minimal performance cost.

**Comment by metabench** [comment]
We should implement this first on `Vector`. `Matrix` uses `Vector` a lot, so Matrix will get sped up.

I'm not that sure how Typed Arrays would be used to optimize `Matrix` but it will become clearer as time goes on. Perhaps we should just use unsigned integer Typed Arrays as indexes to the vectors.

**Comment by mateogianolio** [comment]
My latest commits provide a smooth transition to typed arrays. All methods are still working as they should and they have become significantly faster, which can be seen by comparing benchmark results between branches master and opt-js.

**Comment by mateogianolio** [comment]
I also created an opt-c branch with implementations and benchmarks for vector addition and subtraction in C++, also showing very promising increases in performance.

**Comment by metabench** [comment]
Oh that's very nice indeed. Any idea on the % performance increases?

**Comment by metabench** [comment]
I noticed it was a small change to Matrix.

I was thinking about optimizing Matrix, and I think that a matrix processor would run fastest if it had a typed array that it used for all it's data. However, what I'm thinking of is a substantially different architecture. I was thinking that doing it that way would be a different implementation, and Vector could extend Matrix as a single-dimensional case.

**Comment by mateogianolio** [comment]
I ran your benchmarks (once) with the following results and with the default type of ```Float64Array```:

**opt-js**
* add - 43 ms
* constructor - 35 ms
* equals - 18 ms
* ones - 32 ms
* scale - 39 ms
* subtract - 34 ms
* zeros - 31 ms

**master**
* add - 55 ms
* constructor - 26 ms
* equals - 11 ms
* ones - 167 ms
* scale - 50 ms
* subtract - 53 ms
* zeros - 159 ms

**delta**
* add -12 ms
* constructor +9 ms
* equals +7 ms
* ones -135 ms
* scale -11 ms
* subtract -19 ms
* zeros -128 ms

Most notable improvements in Vector.ones and Vector.zeros.

We should probably start comparing performance with other libraries like [Sylvester](http://sylvester.jcoglan.com) for example.
