### ISSUE TITLE
Hadamard product - Is this applicable to tensors, or just matrices? Other types of products...

### ISSUE THREAD

**Issue by metabench** [mateogianolio/vectorious#135]
@mateogianolio Would you please clarify whether the Hadamard product algorithm that you have written here works fine on tensors of any shape so long as those shapes match?

I did a little reading on the Hadamard product and mostly saw it relating to matrices. Is it still the Hadamard product applied to tensors with other shapes?

Are there other types of product operations that would be particularly useful to implement?

**Comment by mateogianolio** [comment]
As long as the shapes of the tensors are equal I see no reason why it shouldn’t work fine!

**Comment by metabench** [comment]
@mateogianolio My other question is about if there are other products, non-Hadamard products that are worth knowing about and being able to calculate. This would be useful info for API design and implementation.
