### ISSUE TITLE
Policy on API changes

### ISSUE THREAD

**Issue by metabench** [mateogianolio/vectorious#14]
How should we handle changes that could break an app that relies on an API being as it is?

I'm thinking with regards to possibly removing `Vector.prototype.range` and having it as the static method `Vector.range`.

Could it be worth deprecating `Vector.prototype.range` with the goal of eventually removing it?

**Comment by metabench** [comment]
And what about all the API changes recently introduced into master?

**Comment by mateogianolio** [comment]
Let's deprecate it in ```1.2.0``` (I'm suggesting we change the version to ```1.2.0``` once we pull opt-js to master and issue warnings to users using previous versions, since there are quite a few bugs that can lead to unexpected results in the version currently uploaded to ```npm```).

What do you think about that?

**Comment by metabench** [comment]
Though this project has not announced it's using 'semantic versioning', I think it would make sense to follow the rules of that put any changes that will break the API into version 2.0.0.

That would also help those who reference a dependency to the latest version of 1.x.x. It's possible to do that with `package.json`, and I think not having a breaking change in the 1.x.x branch makes the most sense.
