### ISSUE TITLE
Pulling changes from opt-js to master?

### ISSUE THREAD

**Issue by metabench** [mateogianolio/vectorious#15]
@mateogianolio, I've noticed you have rewritten some code in Vector. I'd rewritten parts of it and pushed it to opt-js. I'm not sure if you looked at the code I wrote and then wrote it yourself in a style you prefer, or did not see the code.

I also thought we would be working on the optimized branch, testing it, and then pushing it over to master when a bunch of things were seen to be ready. I still think that is the best way to proceed, and if in the meantime you are making changes to master (and possibly npm) I don't see the problem with that. I think there have been some duplicated efforts recently though, but if we both enjoy coding then maybe that's not a problem either.

Do you have specific ideas about the style of the code, or will it be decided by what works best in benchmarks or tests?

**Comment by mateogianolio** [comment]
Whoops, this was my mistake. I thought I was working in opt-js when in fact I was pushing to master :(

I'm quite flexible with style of code, just write in whatever way you feel most comfortable.

**Comment by mateogianolio** [comment]
I'm not sure how to resolve the conflicts between master and opt-js, should I create a pull request or just do it manually?

**Comment by metabench** [comment]
I suggest we get things running, fast and tested in opt-js, then rebase the master to that opt-js (dev) branch when it's ready, and we've both confirmed with each other it's ready.

**Comment by metabench** [comment]
Perhaps rather than rebasing the master we should pull the changes from the opt-js branch. I could try that in SourceTree, which I use. The changes made in the meantime to master could be problematic, so doing the push requests may mean reverting the master back to where the branches diverged.

I doubt it will be all that difficult to do one way or another when it's time to bring the changes over.

**Comment by mateogianolio** [comment]
I'm closing this since we've reached an agreement on working in the opt-js branch and then merging it with master using a pull request when we are ready for release.
