### ISSUE TITLE
Massive API changes in master

### ISSUE THREAD

**Issue by metabench** [mateogianolio/vectorious#17]
I've noticed that `Vector.prototype.add` no longer does what it used to do, or what is documented.

Currently, it does not add two vectors together, producing a resultant vector, documented as

    // (Vector, Vector) => (Vector)
    Vector.prototype.add = function(vector)

It just does not do that with the new implementation. It adds b to a.

This is taken from the old code:

```
Vector.prototype.add = function(vector) {
    if(this.length !== vector.length)
      throw 'Error: sizes do not match!';
    
    return Vector.construct(this.values.map(function(value, index) {
      return value + vector.values[index];
    }));
  };
```

It constructs a new vector.

**Comment by metabench** [comment]
There are API changes all over the place. A whole bunch of functions no longer produce new vectors, like I think they should.

Testing will help to avoid this problem, but we need to know what we are testing for.

**Comment by metabench** [comment]
I suggest we revert master to sometime back before https://github.com/mateogianolio/vectorious/commit/c6ec56f69b121a986bf2efc1181083076930793f

**Comment by mateogianolio** [comment]
Do you know how to revert master to the point where the branches diverged? If we do that we can automatically merge opt-js and master with a pull request.

**Comment by metabench** [comment]
I use SourceTree and think I'd be able to revert the master without a problem. Id have the master branch open, and individually roll back each of the commits.
