### ISSUE TITLE
API addition: Matrix.determinant()

### ISSUE THREAD

**Issue by mateogianolio** [mateogianolio/vectorious#19]
Matrix determinants are essential to linear algebra (for example calculating areas, volumes, etc) and I'm suggesting we add it to the API as well.

**Comment by metabench** [comment]
Sounds good. I suggest some examples of determinants and other functionality being used to solve some mathematical problems. Personally I've not been all that interested in theoretical maths when I did not think I needed to use it. Showing how some aspects of maths can be used to solve real problems would be very helpful to me and those who have a similar approach (or non-approach) to some aspects of maths.
