### ISSUE TITLE
Is it really an 'n-dimensional matrix' or a 2 dimensional matrix?

### ISSUE THREAD

**Issue by metabench** [mateogianolio/vectorious#20]
As far as I can see, the matrix code is only for 2 dimensions. Is there functionality to support 3 or more dimensions?

**Comment by mateogianolio** [comment]
The n-dimensional refers to vector dimension, an n-dimensional matrix would be called a [tensor](http://en.wikipedia.org/wiki/Tensor). If we want to at a later stage, we could add an object ```Tensor``` that inherits from ```Matrix```, but that's waay ahead in the future.

**Comment by metabench** [comment]
Do you think the project description could be better expressed without it implying it supports tensors?

It may be hard to unambiguously express what dimensionality of dimensionality we are talking about.

**Comment by mateogianolio** [comment]
Sure, why not, but I don't think anyone will make the confusion since tensors are really advanced mathematics almost exclusively used by scientists who wouldn't use this library (they would use Matlab, Mathematica, or equivalents).

**Comment by metabench** [comment]
Maybe those with less advanced maths would make the confusion when they first read about the library.

Also, as the library becomes more capable I expect it to be suitable for more uses. Whether or not scientists actually use it is a different matter.

**Comment by mateogianolio** [comment]
To clarify, the n-dimensional doesn't mean the library is using
n-dimensional arrays, it means the library can be used to describe
n-dimensional space.

A 3x3 matrix is 3-dimensional but it's represented using a two-dimensional
array, just like a vector can be n-dimensional but it's still represented
as a one-dimensional array.

**Comment by metabench** [comment]
OK, so basically it can represent boxes rather than all the superstructures and substructures of nature folded and unfolded into their various quantum superpositions.

**Comment by metabench** [comment]
But on a more practical note, I don't yet understand how Matrix could be used to represent 3D space. If that is possible then a simple example representing a cuboid in 3D space would help a lot.

**Comment by mateogianolio** [comment]
Sure:

```javascript
[
    [0, 0, 0],
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
    [0, 1, 1],
    [1, 1, 0],
    [1, 0, 1],
    [1, 1, 1]
]
```

![unit cube](http://www.petercollingridge.co.uk/sites/files/peter/cube_coords.png)

**Comment by metabench** [comment]
What software did you use to draw/render that?

**Comment by mateogianolio** [comment]
Found the image on google :)

**Comment by waylonflinn** [comment]
@mateogianolio 
Are you interested in taking things in this direction? 

It'd be cool if we could turn this into the JavaScript equivalent of numpy, with transparent GPU support.
Maybe someone would build a new Deep NN library on top of it. :D

**Comment by mateogianolio** [comment]
Yeah, do you think it's possible to build based on what we already have?

**Comment by waylonflinn** [comment]
N-dimensional generalization should be an extension of the stuff I've got in the PR.
Not sure about GPU.

**Comment by metabench** [comment]
@mateogianolio The project description at the top sill refers is "A generalized n-dimensional matrix and vector library in JavaScript."

**Comment by mateogianolio** [comment]
Just saw it, fixed!

**Comment by mateogianolio** [comment]
Tagline has been changed, so this is no longer an issue
