### ISSUE TITLE
I'm confused about the transpose of a matrix.

### ISSUE THREAD

**Issue by supermassiveasshole** [mateogianolio/vectorious#200]
For instance I have a NDArray = array([[1, 0], [0, 1], [0, 0], [0, 0]]). I wonder why it's transpose is [[1, 0, 0, 1], [0, 0, 0 ,0]] instead 0f [[1, 0, 0 ,0], [0, 1, 0, 0]] ?

**Comment by supermassiveasshole** [comment]
Does this method only support for square matrix?

**Comment by mateogianolio** [comment]
It's explained [here](https://stackoverflow.com/a/32034565) better than I will. However, I think you found a bug in `NDMultiIter`. Thanks for your issue.

**Comment by mateogianolio** [comment]
This is actually an issue with `toString`/`toArray`, if you step through the transposed array using `NDIter`, you can see that the indices are correct:

```javascript
const x = array([[1, 0], [0, 1], [0, 0], [0, 0]]);

const iter = new NDIter(x.T);

iter.next(); // { value: 0, done: false }
iter.next(); // { value: 2, done: false }
iter.next(); // { value: 4, done: false }
iter.next(); // { value: 6, done: false }
iter.next(); // { value: 1, done: false }
iter.next(); // { value: 3, done: false }
iter.next(); // { value: 5, done: false }
iter.next(); // { value: 7, done: false }
iter.next(); // { value: undefined, done: true }
```

**Comment by mateogianolio** [comment]
Also, the `copy` method should actually use the iterator to copy the data into c-contiguous order if you need the underlying data to be updated, but that has not been implemented yet. Will create another ticket for this.
