### ISSUE TITLE
More changes to static methods: Vector zeros, Vector ones

### ISSUE THREAD

**Issue by metabench** [mateogianolio/vectorious#22]
These methods also look best as static methods because they have no effect on the instance which they are currently being called from.

This change should appear in `2.0.0`.

I'm writing to confirm this, I think you'll be OK with it, but do you think I should just go ahead and make this kind of change or bring it up as an issue first?

**Comment by mateogianolio** [comment]
I'm OK with it, I think it's good if we bring these kinds of changes up as issues. After we've agreed we can automatically close issues using e.g. ```fix #22``` in the commit message.

**Comment by metabench** [comment]
OK, I'll do it and push the changes to opt-js, and write it up in the https://github.com/mateogianolio/vectorious/blob/opt-js/API.md API doc.

**Comment by metabench** [comment]
Pushed it. Do you think it's worth keeping the issue open until `2.0.0` is released, because at the moment this is something we are still working on despite the code having been written?

**Comment by mateogianolio** [comment]
Ah, didn't know it wouldn't close until merged with master. I see no reason for it to be open so I'm closing it now.
