### ISSUE TITLE
Documentation: Order of Vector and Matrix

### ISSUE THREAD

**Issue by metabench** [mateogianolio/vectorious#23]
I think we should introduce the Vector before the Matrix. Matrix uses Vector, not the other way round, so introducing Vector makes sense to better help users get an understanding of Vectorious.

Also, would you please add a 'documentation' label? I think I can't do it as a committer but you can do it as the project owner.

**Comment by metabench** [comment]
I've added the 'doc' label myself.

**Comment by mateogianolio** [comment]
Yeah, that makes sense.
