### ISSUE TITLE
API Extension Proposal - More Static Methods

### ISSUE THREAD

**Issue by metabench** [mateogianolio/vectorious#25]
I think it's worth having static methods for `add` and various other functions that take two vectors as arguments. This would enable the user to have more flexibility in how they use the library.

This is like what you had changed the API to in `master`, but I'm not suggesting removing the existing API that works from `Vector.prototype`. Having these as static methods in their different forms would be useful. I was not against having those methods as static, just against removing the non-static versions. Now I've moved onto some other things I think it would be a useful addition rather than a bad substitution, given users' expectations.

It would also help with compression of code, but it's a somewhat longwinded explanation, but it's that UglifyJS can compress the names of local variables but not property names. The functions would be writeable as local variables, so would `uglify-js` to smaller code.

It also probably fits in with ideas of functional programming.

Because JavaScript lacks operator overloading, people are left with imperfect answers. I think it's better to provide two of them that would both be useful.

**Comment by mateogianolio** [comment]
538fd786bd211ab0bb13ea6498c71fc72ed7a62f

Added these static methods to ```Vector```:
* ```Vector.add(a, b)```
* ```Vector.subtract(a, b)```
* ```Vector.dot(a, b)```
* ```Vector.angle(a, b)```
* ```Vector.equals(a, b)```
* ```Vector.combine(a, b)```

And these to ```Matrix```:
* ```Matrix.add(a, b)```
* ```Matrix.subtract(a, b)```
* ```Matrix.multiply(a, b)```
* ```Matrix.augment(a, b)```
* ```Matrix.equals(a, b)```

I also added corresponding tests and changed ```Matrix.zeros()``` and ```Matrix.ones()``` to static.

You can run ```gulp javascript``` to generate a compressed version of the code to ```dist/vectorious.js```. It  currently lowers the file size from ```13KB``` to ```8KB```.

**Comment by metabench** [comment]
All these changes LGTM. I'm not so familiar with `dot`, `angle`, and `augment` so should look into those functions some more.
