### ISSUE TITLE
Featured in newsletter

### ISSUE THREAD

**Issue by mateogianolio** [mateogianolio/vectorious#26]
The library appears in the latest issue of JavaScript Weekly: http://javascriptweekly.com/issues/226 :)

**Comment by metabench** [comment]
I see there were 42 unique users yesterday, it seems to have provided a nice little bump.

**Comment by mateogianolio** [comment]
The bump is a bit bigger than that, 400 unique users have visited http://mateogianolio.github.io/vectorious/ today.

**Comment by metabench** [comment]
I'm looking at the data on https://github.com/mateogianolio/vectorious/graphs/traffic

**Comment by mateogianolio** [comment]
Yeah I know but github's stats are cached for some time so they're not up to date. I added google analytics to the site, that's the data I'm looking at.
