### ISSUE TITLE
Prepare master for merge

### ISSUE THREAD

**Issue by mateogianolio** [mateogianolio/vectorious#27]
[Here](http://www.mikeplate.com/2012/04/21/rewind-master-if-you-forgot-to-create-new-branch-in-git/) is a short post on how to rewind the master branch:

```bash
$ git reset --hard 0e4df12
$ git push --force origin master
```

Rewinding to 0e4df12 will enable automatic merging with opt-js.

**Comment by metabench** [comment]
Do you know it would enable automatic merging because that's where the branches diverge?

That's how I see git working and want to confirm with you.

**Comment by mateogianolio** [comment]
I think so, opt-js says it is 20 commits behind master, so if we just rewind to that point it should work out OK.

**Comment by mateogianolio** [comment]
I just reverted to 0e4df12, but it seems opt-js is still 6 commits behind, so I'm going to revert to 1e1ee87

**Comment by mateogianolio** [comment]
That solved it! ```opt-js``` is now mergeable with master :)
