### ISSUE TITLE
Added travis build status

### ISSUE THREAD

**Issue by mateogianolio** [mateogianolio/vectorious#28]
Just added Travis CI for this repository. That means that every time we ```git push``` it will run testing (```mocha```) and update the readme with ```build passing/failing```.

**Comment by metabench** [comment]
Where is the Travis Cl? I don't know much about it, I'm interested in knowing what you did to set it up.

**Comment by mateogianolio** [comment]
I logged in to Travis CI with my github account and then turned it on for this repository by flipping a switch. Then I added this ```.travis.yml``` file

```yaml
language: node_js
node_js:
  - "0.10"
```

and added 

```javascript
"scripts": {
  "test": "./node_modules/mocha/bin/mocha"
},
"dependencies": {
  "mocha": "^2.2.1"
}
```

to ```package.json```.

**Comment by metabench** [comment]
Thanks

**Comment by mateogianolio** [comment]
Here is a link to the Travis page: https://travis-ci.org/mateogianolio/vectorious
