### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by metabench** [mateogianolio/vectorious#3]
@mateogianolio do you have experience with unit testing, maybe the automatic kind that's integrated into github? I'm not experienced in doing that(yet), perhaps it should be a part of this project?

**Comment by mateogianolio** [comment]
I've been meaning to add unit testing using [Mocha](http://mochajs.org). The testing structure would look something like this (example copied from the Mocha website):

```javascript
var assert = require("assert")
describe('Array', function(){
  describe('#indexOf()', function(){
    it('should return -1 when the value is not present', function(){
      assert.equal(-1, [1,2,3].indexOf(5));
      assert.equal(-1, [1,2,3].indexOf(0));
    })
  })
})
```

**Comment by mateogianolio** [comment]
Just added testing for all methods in Vector in /test. Install mocha by running ```$ npm install -g mocha``` and then run ```$ mocha``` from the project root.

**Comment by metabench** [comment]
Looks good so far.

One suggestion is to have some more specific messages than `should work as expected`, such as `calculates V(1, 2, 3) + V(4, 5, 6) = V(5, 7, 9)`.

**Comment by mateogianolio** [comment]
I added tests for all ```Matrix``` methods except for .gauss() which I couldn't get to work properly for the time being.

**Comment by metabench** [comment]
I was going to ask what `gauss` does. That's something worth explaining in the docs.

**Comment by mateogianolio** [comment]
Just got ```.gauss()``` working again.

It converts the matrix to reduced row echelon form (RREF) using [Gauss-Jordan elimination](http://en.wikipedia.org/wiki/Gaussian_elimination). This is useful for a lot of things like computing matrix determinants, inverses and solving systems of linear equations.

**Comment by mateogianolio** [comment]
A complete testing suite has been added so I consider this issue resolved.

**Comment by metabench** [comment]
I'm not so sure. Testing will be an ongoing process so it may be worth having an ongoing issue as the discussion thread where we talk about it.

Just a suggestion, because anything to do with testing could be put in its own issue, or this issue could be reopened.

**Comment by mateogianolio** [comment]
I suggest we create a new issue if a build is failing, because right now testing is stable.
