### ISSUE TITLE
Further Progress - Versions 3 and 4

### ISSUE THREAD

**Issue by metabench** [mateogianolio/vectorious#36]
Version 2.1.0 of node's Nan (https://github.com/nodejs/nan) has introduced Nan::TypedArrayContents (https://github.com/nodejs/nan/blob/master/doc/v8_misc.md#nantypedarraycontents), which provides stability and a seemingly convenient interface to access Typed Arrays from within C++ addons.

From the look of things, much optimization has been done in versions 2.x.x. Though the version 3 milestone says 'fully optimized' I don't think we would be sure of reaching that because it would take a while longer to prove everything is at maximum optimization. Perhaps it means 'fully optimized' within the scope of how much optimization we will do to the JavaScript code.

I am keen on using Typed Arrays and accessing them from C++ code to speed up some operations. It will also require care to ensure that the project keeps the right structure and compatibility, as it becomes more complicated by introducing compiled C++ code.

**Comment by waylonflinn** [comment]
@watmough

**Comment by mateogianolio** [comment]
Hey, thank you for the kind words. This looks interesting. If you feel comfortable enough to implement it you can submit a pull request.

**Comment by metabench** [comment]
@waylonflinn I think using one large typed array is a good direction to go in. It's a big change to the API and current structure. My optimizations have been to do with speeding up the operation of the library while keeping it functionally the same. It would be good to see the library moving towards very fast performance where possible, and this looks like one such place.

It's better to make architectural improvements now, before C++ code has been written.

**Comment by waylonflinn** [comment]
Thanks guys!
Got a little prototype working. 20x speed up so far.

Here's a preview:
![vectorious-benchmark](https://cloud.githubusercontent.com/assets/804108/11283951/d3c9cda2-8ecc-11e5-9374-0e5790d177ae.png)

**Comment by waylonflinn** [comment]
You can run these benchmarks here: [Matrix Benchmarks](http://waylonflinn.github.io/js-matrix-benchmarks/matrix_benchmark.html) 

* currently running on a 128x128 matrix
* only Multiplication is implemented
* takes several seconds to run

**Comment by mateogianolio** [comment]
You should update the benchmarks to use the latest dist

**Comment by waylonflinn** [comment]
Will do. Working on getting the other operations benchmarked.

**Comment by waylonflinn** [comment]
New browser benchmarks: [Javascript Matrix Library Benchmarks](http://waylonflinn.github.io/js-matrix-benchmarks/matrix_benchmark.html)
Now includes:
* [numeric](http://www.numericjs.com/)
* Vectorious
* [Sylvester](http://sylvester.jcoglan.com/)
* [math.js](http://mathjs.org/)

Vectorious now beats everyone at matrix multiply, but get's crushed by numeric on Inverse and Determinant. We should see why numeric's code is so fast, and copy what they do.

![image](https://cloud.githubusercontent.com/assets/804108/11375692/2b354246-92a2-11e5-85d6-8764b210ad82.png)

**Comment by waylonflinn** [comment]
In case it's not clear from the code the data access pattern for our matrices is now:

```javascript

var row_count = this.shape[0],
    column_count = this.shape[1];

// get data for row i and column j
d_ij = this.data[i * column_count + j];
```

Hopefully it's pretty straightforward to adapt their code.

**Comment by metabench** [comment]
I have seen how some of the functions now operate in-place on two given matrices. I see how that will improve performance in places. My concern is that it looses too much flexibility. I know I have not been paying this project nearly as much attention as other contributors and have not been writing code for it recently but I think it's still worth me stating my opinion.

My opinion is based somewhat on the lower level operations available, such as SIMD. If you look at https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=add&expand=59,79,2527,82,91&techs=AVX2 you will see that the _mm256_add_epi64 instruction will 'Add packed 64-bit integers in a and b, and store the results in dst'.

While some operations would benefit from less memory use by not producing extra vectors or matrices, it would render the system unsuitable for some other operations.

While I see that creating a new data structure to place the result in is an inefficiency, I suggest that writing the result to an existing data structure would not have that problem and would make the application code clearer in terms of the data structures it initialises.

Even if it were desirable to support both in-place and writing to a separate result, the question would be about what API would best support this. Would it involve writing more functions with different names? Polymorphism would make for a nice API, however I have doubts about how well it would work for performance critical code.

@mateogianolio Is this something that it would be better to have, and would it be worth finding a way to include it in Vectorious?

**Comment by metabench** [comment]
@mateogianolio Plus, what does NumPy support in terms of where the results get assigned or if it will create a new data structure? It would be worth making the library similar to NumPy where NumPy is already doing some things well, if possible.

**Comment by mateogianolio** [comment]
I have changed some functions to in-place to avoid moving memory. This has been based on how the BLAS routines work.

For example, `Vector`/`Matrix` addition and subtraction corresponds to `axpy (n, alpha, x, inc_x, y, inc_y)` which scales the vector `x` with `alpha` and adds to `y`, putting the result in `y`. I used the same reasoning for other functions.

Moving and creating memory is not a problem for smaller types, but for matrices containing tens of millions of elements, the difference is significant.

If the function is quicker in-place, a static version of the function should exist that returns a new instance.

E.g. `Vector.prototype.add(vector)` and `Vector.add(a, b)`

**Comment by waylonflinn** [comment]
I agree that in-place shouldn't be the default. Numpy allows you to provide an optional 'out' parameter to store results, this gives the same performance gains when a result matrix can be reused (this is the method I used while developing the new multiply, because it does matter for lots of small matrix multiplies)



—

**Comment by waylonflinn** [comment]
I believe that if you call [`TypedArray.fill`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/fill) and fill the provided `out` parameter with zeros first you can use it as the third matrix (`C`) in the GEMM functions, without a large performance penalty.

**Comment by mateogianolio** [comment]
I'm a bit confused, matrix multiply was never in-place (and never will be) since the resulting dimensions are different.

**Comment by mateogianolio** [comment]
That is, the static function for matrix multiply is equivalent to the prototype function. It's just there as an alias :)

**Comment by mateogianolio** [comment]
Furthermore, I think `a.add(b)` implies that you want to add `b` to `a` while `Vector.add(a, b)` implies that you want the result as a new vector. Is this unclear?

**Comment by waylonflinn** [comment]
Ah, yeah you're right. It isn't in-place right now. :)

If you wanted to implement the general idea of having a user-supplied container (as an alternative to in-place operations) that's how you could to it for the matrix multiply. Actually, looking at the GEMM specification again, there's a better way than I suggested. Just pass zero for the beta parameter.

![GEMM Formula](https://software.intel.com/sites/default/files/did_feeds_images/185A709A-A64B-4814-82B2-98FF101FEE1A/7ABBBC64-E2AC-46BF-A6F8-B844A889F217.gif)

Image from [Multiplying Matrices Using dgemm](https://software.intel.com/en-us/node/429920)

**Comment by waylonflinn** [comment]
You're thinking makes sense (and I've gone back and forth on this over the past few days), but it breaks the conventions that people are used to in some cases. It might be worthwhile to examine how other modern implementations handle this. The first thing that comes to mind is [Julia](http://julialang.org/)

**Comment by mateogianolio** [comment]
If we had operator overloading in JavaScript, which python does and numpy uses, we could simply do `a += b` for in-place and `a + b` for a new instance.

**Comment by mateogianolio** [comment]
Your are right that `beta` should default to zero in GEMM. I'm a bit concerned about the performance of moving memory in JavaScript. Maybe we should write a memcpy binding in C++?

Benchmarks:
```
> vectorious@4.0.0 benchmark /Users/mg/Projects/javascript/vectorious
> node ./benchmarks/vector.js && node ./benchmarks/matrix.js

data = randomArray(1024)
a = Vector.ones(data)
b = Vector.ones(data).scale(2)

Vector.zeros(1024) x 166,533 ops/sec ±1.65% (78 runs sampled)
Vector.ones(1024) x 169,941 ops/sec ±1.09% (79 runs sampled)
Vector.range(0, 1024) x 50,621 ops/sec ±2.65% (82 runs sampled)
Vector.combine(a, b) x 60,810 ops/sec ±5.80% (66 runs sampled)
Vector.add(a, b) x 177,917 ops/sec ±6.83% (57 runs sampled)
a.add(b) x 3,909,765 ops/sec ±0.91% (90 runs sampled)
Vector.subtract(a, b) x 165,158 ops/sec ±9.19% (51 runs sampled)
a.subtract(b) x 3,999,375 ops/sec ±0.81% (88 runs sampled)
Vector.scale(a, Math.random()) x 19,977 ops/sec ±0.94% (89 runs sampled)
a.scale(Math.random()) x 5,001,924 ops/sec ±0.73% (93 runs sampled)
a.normalize() x 3,702,570 ops/sec ±0.92% (89 runs sampled)
a.dot(b) x 4,581,113 ops/sec ±0.76% (90 runs sampled)
a.magnitude() x 10,478,732 ops/sec ±0.76% (91 runs sampled)
a.angle(b) x 902,189 ops/sec ±0.74% (87 runs sampled)
Vector.project(a, b) x 152,484 ops/sec ±10.12% (56 runs sampled)
a.project(b) x 1,684,157 ops/sec ±1.95% (88 runs sampled)

data = randomArray(128, 128)
a = Matrix(data)
b = Matrix(data).scale(2)

Matrix.identity(128) x 9,206 ops/sec ±5.35% (81 runs sampled)
Matrix.magic(128) x 2,229 ops/sec ±5.25% (82 runs sampled)
Matrix.zeros(128, 128) x 9,634 ops/sec ±4.20% (83 runs sampled)
Matrix.ones(128, 128) x 9,571 ops/sec ±4.17% (83 runs sampled)
Matrix.augment(a, b) x 3,356 ops/sec ±3.92% (78 runs sampled)
Matrix.add(a, b) x 10,250 ops/sec ±4.99% (73 runs sampled)
a.add(b) x 145,362 ops/sec ±0.67% (96 runs sampled)
Matrix.subtract(a, b) x 10,504 ops/sec ±4.96% (81 runs sampled)
a.subtract(b) x 146,280 ops/sec ±0.62% (98 runs sampled)
Matrix.scale(Math.random()) x 10,807 ops/sec ±6.61% (78 runs sampled)
a.scale(Math.random()) x 204,706 ops/sec ±1.00% (98 runs sampled)
a.multiply(b) x 5,815 ops/sec ±5.40% (83 runs sampled)
Matrix.transpose(a) x 9,066 ops/sec ±5.97% (83 runs sampled)
a.transpose() x 43,982 ops/sec ±1.10% (95 runs sampled)
a.gauss() x 6,683 ops/sec ±3.92% (86 runs sampled)
a.lu() x 19.76 ops/sec ±0.93% (37 runs sampled)
a.determinant() x 19.56 ops/sec ±0.85% (37 runs sampled)
a.diag() x 612,655 ops/sec ±1.77% (68 runs sampled)
a.trace() x 467,518 ops/sec ±2.88% (71 runs sampled)
a.swap(i, j) x 22,348 ops/sec ±1.72% (37 runs sampled)
```
