### ISSUE TITLE
Matrix: Eigenvalues & eigenvectors

### ISSUE THREAD

**Issue by mateogianolio** [mateogianolio/vectorious#39]
https://en.wikipedia.org/wiki/Eigenvalue_algorithm
https://en.wikipedia.org/wiki/QR_algorithm

**Comment by mateogianolio** [comment]
"Block Multishift QR Algorithm"  http://www.netlib.org/lapack/lawnspdf/lawn08.pdf

**Comment by mateogianolio** [comment]
[Symmetric QR Algorithm with Permutations](http://arxiv.org/pdf/1402.5086v1.pdf) with accompanying [MATLAB implementation](http://de.mathworks.com/matlabcentral/fileexchange/45642-symmetric-qr-algorithm-with-permutations)

**Comment by mateogianolio** [comment]
[Jacobi Eigenvalue Algorithm](https://github.com/ttrfstud/jacobi-eigenvalue) in javascript.

**Comment by lucidrains** [comment]
which algorithm is the best one?

**Comment by mateogianolio** [comment]
I think the Jacobi version is good because the givens rotation can be accelerated with BLAS (relevant routines ?rot/?rotg/?rotmg).

[This wikipedia article](https://en.m.wikipedia.org/wiki/Jacobi_eigenvalue_algorithm) also contains pseudocode describing the procedure.

**Comment by lucidrains** [comment]
oo nice! i think i'll work on that in my spare time then :)

**Comment by backspaces** [comment]
Any progress on implementation? We need eigenvalues/vectors for work we're doing. Numeric seems to be on hold and is pretty hard to grok due to sparse docs.

**Comment by mateogianolio** [comment]
Hi @backspaces, unfortunately not but I might try to implement it this weekend. I can't really promise anything though. I'm glad you've found interest in this library!

**Comment by jloveric** [comment]
Are you using LAPACK as in nlapack?  Lapack already has eigenvalue/vector solvers http://www.netlib.org/lapack/explore-html/d9/d8e/group__double_g_eeigen.html
