### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by metabench** [mateogianolio/vectorious#4]
Currently the readme file has got plenty of examples, but it lacks API documentation.

I suggest we document the API in a format similar to https://github.com/metabench/jsgui-node-png.

**Comment by metabench** [comment]
I plan on putting API documentation into the readme.

**Comment by mateogianolio** [comment]
See wiki or install jsdox (`npm i jsdox -g`) and run `jsdox vector.js matrix.js`
