### ISSUE TITLE
Polyfill Missing TypedArray Methods

### ISSUE THREAD

**Issue by waylonflinn** [mateogianolio/vectorious#41]
Some of the newer TypedArray methods (like `slice` and `fill`) aren't implemented in all browsers. We should add a polyfill for these.

**Comment by mateogianolio** [comment]
I think we should have some kind of limit on which browser versions to provide backwards compatibility for. Providing polyfills for too many functions will bloat the library (`slice` and `fill` should be easy enough to polyfill).

**Comment by waylonflinn** [comment]
:+1: for minimum supported browser versions

**Comment by waylonflinn** [comment]
Something like this could be cool for keeping track of that: https://ci.testling.com/

Taken from here: https://github.com/substack/typedarray

**Comment by mateogianolio** [comment]
Shim for `TypedArray` implementing all functionality needed: https://github.com/ghcjs/shims/blob/master/lib/typedarray/typedarray.js

**Comment by mateogianolio** [comment]
Typed Arrays are something browsers are supposed to implement according to the ecmascript standard, and therefore I don't think it is appropriate to provide polyfills for these features. Closing this for now.
