### ISSUE TITLE
Machine learning

### ISSUE THREAD

**Issue by mateogianolio** [mateogianolio/vectorious#45]
> Discussion regarding the use of **Vectorious** for [machine learning](https://en.wikipedia.org/wiki/Machine_learning).

**Topics**
- [Supervised learning](https://en.wikipedia.org/wiki/Supervised_learning)
- [Clustering](https://en.wikipedia.org/wiki/Cluster_analysis)
- [Dimensionality reduction](https://en.wikipedia.org/wiki/Dimensionality_reduction)
- [Anomaly detection](https://en.wikipedia.org/wiki/Anomaly_detection)
- [Neural nets](https://en.wikipedia.org/wiki/Artificial_neural_network)

Found [this article](http://briandolhansky.com/blog/2014/10/30/artificial-neural-networks-matrix-form-part-5) explaining how to implement a simple neural network in matrix form, would be cool to have as an example in the future :)

**Comment by waylonflinn** [comment]
Pretty cool. Nice concise matrix based presentation.

Here's the reference I've been using: 
Neural Networks and Deep Learning Chapter 2, [How the backpropagation algorithm works](http://neuralnetworksanddeeplearning.com/chap2.html)

**Comment by mateogianolio** [comment]
#52

**Comment by mateogianolio** [comment]
#60

**Comment by mateogianolio** [comment]
#61

**Comment by mateogianolio** [comment]
Moved to discussions.
