### ISSUE TITLE
Optimization suggestion: Don't make as many function calls

### ISSUE THREAD

**Issue by metabench** [mateogianolio/vectorious#6]
I am seeing a lot of code like `this.values.map(function(`. Using more procedural code would probably speed it up. A for loop does not need to call a function on each iteration. Benchmarking would tell if this actually does make for an improvement in the speed, but I think it's an avenue worth perusing.

Though we could (probably) use an equivalent of `map` in C or C++, it's easier to port functions that correspond almost directly with simple, idiomatic C code.

**Comment by mateogianolio** [comment]
Yes, all functional calls (```map```, ```forEach```, ```reduce```, etc) should be converted to loops for performance. When I started building the library the primary focus wasn't speed, but rather ease of use and keeping all object methods as short as possible.

**Comment by metabench** [comment]
I've found that by using a for loop to add the vectors (opt 2), along with caching the reference to the `values` array, I got a 439% speedup compared to opt 1 code. Compared to unoptimized code it's a 2428% speedup so far.
