### ISSUE TITLE
Matrix: multiplication performance

### ISSUE THREAD

**Issue by mateogianolio** [mateogianolio/vectorious#74]
A switch to using the [Strassen algorithm](https://en.wikipedia.org/wiki/Strassen_algorithm) will reduce the algorithmic complexity from **O**(n<sup>3</sup>) to **O**(n<sup>2.81</sup>).

**Comment by bartvanandel** [comment]
If you're willing to go that path, maybe switching to [Coppersmith & Winograd](https://en.wikipedia.org/wiki/Coppersmith%E2%80%93Winograd_algorithm) is even better. Strassen was the first to find an algorithm better than O(n^3), this led to more research finding even better algoritms. It's actually stated in the Wikipedia link you posted.

**Comment by Beraliv** [comment]
If I have time, I would contribute to it
As I learnt it in uni and I am kind of interested in making an implementation, if you're not against

**Comment by mateogianolio** [comment]
I think the Strassen algorithm is the best choice for most applications.

From Wikipedia:

> Algorithms with better asymptotic running time than the Strassen algorithm are rarely used in practice, because the large constant factors in their running times make them impractical.
