### ISSUE TITLE
Add .x, .y and .z -properties to Vector-objects

### ISSUE THREAD

**Issue by ahvonenj** [mateogianolio/vectorious#76]
I think it would be useful by a great margin to have a quick access to the first three `Vector` elements by implementing `.x`, `.y` and `.z` -properties for the Vector object.

It could work like this

```
var a = new Vector([5, 10]);
var b = new Vector([1, 2, 3]);

console.log(a.x, a.y);  // 5, 10
console.log(b.x, b.y, b.z); // 1, 2, 3

console.log(a.z); // undefined / null
```

Basically the `.x`, `.y` and `.z` -properties would be aliases for `v[0]`, `v[1]` and `v[2]` or their `.get()`-equivalents.

I understand that the array-implementation of the vector components makes the vectors more generic, but as 2D-vectors and 3D-vectors are the most common ones used, it would make sense to have the shorthands. It wouldn't hurt, even if the vectors were, say, 16-dimensional, as you could still access any of the vector components like how it is done right now. These shorthands would only affect the first three components of any vectorious Vector object.

**Comment by mateogianolio** [comment]
Should be easy enough to implement. Thanks for your input!
