### ISSUE TITLE
Vector immutability or cloning

### ISSUE THREAD

**Issue by ahvonenj** [mateogianolio/vectorious#77]
Usually in vector libraries, the vector methods do not change the original vector.

Example

```
var a = new Vector([10, 20]);
var b = a.scale(2); // Also changes a, when in my opinion, it should not
```

As immutability is somewhat annoying and time consuming to implement - some JavaScript vector libraries work around the problem by implementing `.clone()`-method like this

```
var a = new Vector([10, 20]);
var b = a.clone().scale(2); // Now a is still [10, 20] and b is scaled a
```

So I suggest implementing a `.clone()`-method for `Vector`.

**Comment by mateogianolio** [comment]
All right, the way it works now is that immutable operations are achieved by calling the static version of the functions e.g. `var b = Vector.scale(a, 2);`. Initially I was focusing almost exclusively on performance and not ease of use, but from the input I've received this can be confusing so I might have to add the `clone()` feature you are proposing.

**Comment by ahvonenj** [comment]
Oh, I did not know about the static methods being the solution to this, great! The `clone()`-feature might still come in handy though, if it is not too big of a performance loss.

**Comment by mateogianolio** [comment]
Closing this for now, will reopen (or create a new one) if necessary later on.
