### ISSUE TITLE
Is vector projection a bit off / broken, or is it just my code?

### ISSUE THREAD

**Issue by ahvonenj** [mateogianolio/vectorious#78]
So first of all, look at this gif I made here: http://puu.sh/qkSqJ/8034b263da.gif

I am projecting the vector C->A (cyan) to the vector C->B (magenta). The projected vector (P) is the red one and the green vector is vector rejection A->P.

So basically, shouldn't the projected vector P always line up exactly with the vector C->B and not just when A is close to B? The line-up error increases as A goes further away from B.

Again, it could be my code, so here it is:

```
var va = new Vector([400, 400]);
var vb = new Vector([500, 650]);
var vc = new Vector([250, 250]);

var vp = Vector.project(va, vb);

// After this I just draw a webgl-line, for example,
// from (vc.get(0), vc.get(1)) to (vp.get(0), vp.get(1))
```

Of course, the vector `va` changes values as I click around.

I am suspecting that it's the library's fault, because the projection is very close to what it should be and I don't see me offsetting it in my code. Then again, maybe I am missing something integral regarding how to do this projection in the first place - very sorry if that is the case.

The length of the projected vector seems to be correct, but I am guessing that there could be an error with the normalization or the dot product function.

I also tried doing the projection manually like this, by following wikipedia ([Vector projection](https://en.wikipedia.org/wiki/Vector_projection)):

```
var va = new Vector([400, 400]);
var vb = new Vector([500, 650]);
var vc = new Vector([250, 250]);

var vbn = Vector.normalize(vb);
var l = Vector.dot(va, vbn);
var vp = Vector.scale(vbn, l);

// After this I just draw a webgl-line, for example,
// from (vc.get(0), vc.get(1)) to (vp.get(0), vp.get(1))
```

But this results in to the exact same scenario as shown in the gif.

`Vectorious version: vectorious-4.3.2.min.js`

**Comment by mateogianolio** [comment]
Hey, nice visualisation! You have to adjust your coordinate basis (see e.g. [Change of basis](https://en.wikipedia.org/wiki/Change_of_basis)). 

The projection formula assumes your basis is `(0, 0)`, which you can see by changing your point `C` to `(0, 0)`.

To fix it in your example, you can subtract `C` (your reference point) from `A` and `B`, perform the projection and then add `C` to the resulting vector:

```javascript
var va0 = Vector.subtract(va, vc);
var vb0 = Vector.subtract(vb, vc);

vp = Vector.add(Vector.project(va0, vb0), vc);
```

Let me know if it works or if you want me to clarify.

**Comment by ahvonenj** [comment]
That did it, thanks a lot! I always forget the coordinate basis thing... I wish it worked automatically somehow.

Anyways, here is the fixed program: http://puu.sh/qlcEb/e28397b503.gif

**Comment by ahvonenj** [comment]
Hmm this actually got me thinking... would it be a stupid idea to have a `rebase`-alias for the subtract method for vectors? Maybe it's just me thinking it would be handy, but I am thinking that it would make vector calculations in code more readable, if you actually had something like `var va0 = Vector.rebase(va, vc)` instead of `subtract`, which is in my opinion a lot more ambiguous.

I think I will just add this alias to my own copy of the library.
