### ISSUE TITLE
API Change Suggestion: Vector range

### ISSUE THREAD

**Issue by metabench** [mateogianolio/vectorious#8]
The readme says 'Create a vector containing the range from start to end in steps of step (optional).' This looks more like it should be a static method of Vector, rather than a method of a Vector instance. To do that it would be assigned to `Vector` rather than `Vector.prototype`

Looking at the code, `range` pushes values onto an existing Vector instance. That behaviour is not defined in the API, but for the moment it's being used in my first `vector.range` example. I got unexpected results where I tried to add the range 100 to 105, using `.range(100, 105)`, but it only pushed the numbers 100 to 103 onto the vector.

We should clarify what `range` is supposed to do, then get it to do that, possibly using a static method.

**Comment by mateogianolio** [comment]
Why static? I fixed your issue in my latest commit.

Usage example:

```javascript
var vector = new vectorious.Vector().range(0, 5)
// vector contains [0, 1, 2, 3, 4]

var vector = new vectorious.Vector().range(5, 0)
// vector contains [5, 4, 3, 2, 1]

var vector = new vectorious.Vector().range(0, 3, 10)
// vector contains [0, 3, 6, 9]
```

**Comment by metabench** [comment]
The reason I think it may be better as a static method has to do with me not being sure what it's for. It the result is based from an existing instance of a Vector then it should not be static. However, if we want to be able to call

    Vector.range(0, 5)

to get a new vector in that range, than a static method would be way to do it.

**Comment by metabench** [comment]
I'm looking at this code, and it's `Vector.range = Vector.prototype.range`.

While still supporting the existing API makes sense in terms of not breaking anything unexpectedly, I was suggesting an API change where `range` in its current form is not a method of a vector instance.

What do you think about making breaking API changes? Is it acceptable to do when incrementing the major version number or would you prefer to avoid it by keeping `range` as a function of the Vector prototype?

**Comment by mateogianolio** [comment]
I see no reason why we can't keep it as a function of the prototype for backwards compatibility? It's barely one line of code.

**Comment by metabench** [comment]
The reason not to keep it is in order to have a simpler API, which in the long run would make the programmer's job easier.

I think releasing something that breaks backwards compatibility with too little notice is the wrong thing to do. However, a version 2 was released that said the feature was depricated in its documentation, possibly have a version 3 print a warning when it's used, and then a version 4 remove it entirely, would lead to the simpler eventual API. Or it could be done quicker than that, but still with warnings in documentation.

Over the long run software projects can be bogged down by having to support old APIs. The alternative provides less stability.

**Comment by mateogianolio** [comment]
You are right, maybe we could unpublish it from npm and let ```1.0.0``` be the version with typed arrays? Then we wouldn't have to think about backwards compatibility until after release. Or is that a stupid move?

**Comment by metabench** [comment]
I don't think we should unpublish it. I think we should proceed with stability from the point we have now. There have been quite a lot of downloads of the library.

I think for the moment we should keep the code supporting both versions, and document only the approved version in the docs. But I think we should get rid of the current `vector.range` quite soon, as it's better in the long run if it's not there.

**Comment by mateogianolio** [comment]
No need for this to be open any more.
