### ISSUE TITLE
Select a matrix subset

### ISSUE THREAD

**Issue by rollingstone80** [mateogianolio/vectorious#83]
How do I select and return a subset of a matrix? I.e. a selection of rows and columns...

Thanks

Enrico

**Comment by mateogianolio** [comment]
This is definitely a missing feature. Do you have any suggestions on how you'd like it implemented?

Examples:

* [JavaScript (ndarray)](https://github.com/scijs/ndarray#slicing)
* [Python (numpy)](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)
* [Matlab](https://se.mathworks.com/company/newsletters/articles/matrix-indexing-in-matlab.html)
* [Julia](http://docs.julialang.org/en/release-0.5/manual/arrays/#concatenation)

**Comment by rollingstone80** [comment]
Hi Mateo, in my project I'm using a very simple function that looks like this:
`function subset(matrix, rowRange, colRange) {
    
    const rows = matrix.shape[0];
    const cols = matrix.shape[1];
    matrix = matrix.toArray();
    const matrixSubset = [];

    let i = 0;
    rowRange.forEach(function(rowValue) {
        matrixSubset.push([])
        colRange.forEach(function(colValue) {
            matrixSubset[i].push(matrix[rowValue - 1][colValue - 1]);
        })
        i++;
    })

    return new Matrix(matrixSubset);

}`

Where I pass to the subset function the original matrix and two arrays that represent the rows and columns I want to select. As you can see, the arrays in the example are not "zero-based", i.e. if I want to extract the first 2 rows and the first column of a given matrix I would pass [1,2] and [1]. It's just more intuitive to me.

**Comment by mateogianolio** [comment]
See `slice` method.
