### ISSUE TITLE
Build Filename Without Version Number

### ISSUE THREAD

**Issue by pvnr0082t** [mateogianolio/vectorious#88]
Hi @mateogianolio ,
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs). This lib had already been hosted in cdnjs.
Would it be possible to please remove the version number from the concatenated library file names (e.g., "vectorious-0.6.1.min.js" becomes "vectorious.min.js")? This is not particularly helpful and creates manual annoyances when upgrading to newer versions of the library. It will also better for auto-updater in cdnjs to update new release automatically in the future. Thank you.

https://github.com/cdnjs/cdnjs/issues/10013

**Comment by mateogianolio** [comment]
Hey @pvnr0082t! Should I remove the version number from all releases (on the releases page), or just in the `dist/` folder in the repo?

**Comment by pvnr0082t** [comment]
@mateogianolio You can just remove files with version number under `dist` folder and keep the version number on releases page. Thanks.
